@URL_DEV=http://localhost:3055/v1/api/

### signup
POST {{URL_DEV}}shop/signup
Content-Type: application/json
x-api-key: 59bfdacc35582d6b737f2739acea4e97fcfc2dec544eaccb61871264132eeac942f55c0dabf8578b419f1b229de8b59c81675aaa3dc24237e513e84898afd26e

{
    "name": "ShopTIPS",
    "email": "shoptips@gmail.com",
    "password": "abc123"
}